Основная структура сайта
study-fe/static-sites pull request #2
Opened 2019-03-27 09:49 UTC by NikaCrimea

2019-03-27 09:59 UTC, mokcrimea commented on Nika/css/style.css
> +background-image: url(/Users/veronika/Documents/FUD/images/bottega-sicula-wpcf_1200x700.jpg);
как нам увидеть это ? 
не используй абсолютные пути

2019-03-27 10:01 UTC, seyar commented on Nika/css/style.css
> +text-decoration: none;
можно еще попросить отступы ставить для правил?
```
a {
    text-decoration: none;
}
```

2019-03-27 10:01 UTC, NikaCrimea commented on Nika/css/style.css
> +background-image: url(/Users/veronika/Documents/FUD/images/bottega-sicula-wpcf_1200x700.jpg);
я уже комитнула изменения

2019-03-27 10:02 UTC, NikaCrimea commented on Nika/css/style.css
> +text-decoration: none;
ага, кажется они ставились, просто я их стирала)

2019-03-27 10:03 UTC, seyar commented on Nika/css/style.css
> +background-image: url(/Users/veronika/Documents/FUD/images/xdefault.png.pagespeed.ic.uZXACHvpgj.png);
Давай использовать просто короткое `background`

2019-03-27 10:05 UTC, seyar commented on Nika/css/style.css
> +.image-1 {
тут напрашивается наследование селекторов. 
Один стиль для всех имеджей и отдельно по каждому где у них есть особенности

2019-03-27 10:05 UTC, mokcrimea commented on Nika/css/style.css
> +text-decoration: none;
Можно сюда закинуть - http://csscomb.com/online/, добавит отступы по нормальному. 
Это если плагин не настроен

2019-03-27 10:06 UTC, mokcrimea commented on Nika/css/style.css
> +background-image: url(/Users/veronika/Documents/FUD/images/bottega-sicula-wpcf_1200x700.jpg);
А как ты их комитнула, если мы их тут не видим ?

2019-03-27 10:06 UTC, seyar commented on Nika/index.html
> +                        <div><a> > DISCOVER THE PROJECT</a></div>
лишняя треугольная скобка

2019-03-27 10:07 UTC, seyar commented on Nika/index.html
> +                    </div>
тут лишний закрывающийся див. Или не?

2019-03-27 10:07 UTC, NikaCrimea commented on Nika/css/style.css
> +text-decoration: none;
плагин настроен)

2019-03-27 10:08 UTC, NikaCrimea commented on Nika/index.html
> +                        <div><a> > DISCOVER THE PROJECT</a></div>
Это такой текст на кнопке,  я с сайта брала)

2019-03-27 10:08 UTC, mokcrimea commented on Nika/css/style.css
> +padding-left: 60%;
а почему в % ?

2019-03-27 10:08 UTC, seyar commented on Nika/index.html
> +                    <hr align="left" width="225" size="1" color="#4d4d4d">
ооо, я вспомнил свой 1996й год.

я про атрибуты в html

2019-03-27 10:09 UTC, seyar commented on Nika/index.html
> +<!DOCTYPE html>
в этом файле все чистенько и аккуратненько, как у отличницы

2019-03-27 10:10 UTC, seyar commented on Nika/index.html
> +                        <div><a> > DISCOVER THE PROJECT</a></div>
значит ты неправильно сделала. Посмотри он также рендерится как ты хочешь

2019-03-27 10:10 UTC, mokcrimea commented on Nika/css/style.css
> +margin-top: -4%;
Не очень хорошая практика использовать отрицательные отступы в margin. Можешь изменить расположение элементов, что бы этого избежать ?

Ну и тоже не понятно почему %

2019-03-27 10:11 UTC, mokcrimea commented on Nika/css/style.css
> +z-index: 300;
Зачем `z-index` ?

2019-03-27 10:14 UTC, NikaCrimea commented on Nika/css/style.css
> +background-image: url(/Users/veronika/Documents/FUD/images/bottega-sicula-wpcf_1200x700.jpg);
небольшое недоразумение вышло)
У меня вопрос - Я в VS Code копирую relative path картинки и использую его в коде, в итоге картинка все равно не отображается, что может быть не так?

2019-03-27 10:20 UTC, NikaCrimea commented on Nika/index.html
> +                    </div>
не, не лишний

2019-03-27 10:21 UTC, NikaCrimea commented on Nika/css/style.css
> +padding-left: 60%;
если я ставлю в "px", то при изменении размера экрана блок не смещается, а остается закрепленным на месте

2019-03-27 10:22 UTC, NikaCrimea commented on Nika/css/style.css
> +margin-top: -4%;
попробую

2019-03-27 10:24 UTC, NikaCrimea commented on Nika/css/style.css
> +z-index: 300;
потому что логотип накладывается на "menu-shell"

2019-03-27 10:25 UTC, seyar commented on Nika/index.html
> +                    </div>
тогда что-то пошло не так с отступами

2019-03-27 10:28 UTC, seyar commented on Nika/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1">
насколько я помню `initial-scale=1` говорит мобильным телефонам что "тут нельзя зумить сайт итак норм"
т.е пользователи мобильных девайсов тебя проклянут. Но могу ошибаться, лень искать на htmlbook :)

2019-03-27 10:32 UTC, NikaCrimea commented on Nika/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1">
да, убрать это? Я установила плагин, который автоматом выстраивает основную структуру html и просто не убрала это свойство)

2019-03-27 10:56 UTC, seyar commented on Nika/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1">
я больше советую разобраться что это делает. А так-то можно и оставить

2019-03-27 13:52 UTC, mokcrimea commented on Nika/css/style.css
> +z-index: 300;
а z-index: 1 не достаточно в таком случае ?

2019-03-27 13:55 UTC, mokcrimea commented on Nika/index.html
> +                    </div>
для html тоже есть плагин, который форматирует все правильно, поищи

2019-03-27 13:56 UTC, mokcrimea commented on Nika/index.html
> +</html>
поищи в настройках редактора, что бы при сохранении добавлял пустую строку в конце файла

2019-03-27 15:12 UTC, NikaCrimea commented on Nika/css/style.css
> +background-image: url(/Users/veronika/Documents/FUD/images/bottega-sicula-wpcf_1200x700.jpg);
так что на счет картинок, вы их видите?) я посмотрела файл через добавление http://htmlpreview.github.io/?
к ссылке файла
все картинки отображаются)

2019-03-27 19:10 UTC, NikaCrimea commented on Nika/css/style.css
> +.image-1 {
не получилось сделать чтобы наследовались селекторы, когда я использую просто background. Пришлось оставить background-image.

2019-03-27 19:11 UTC, NikaCrimea commented on Nika/css/style.css
> +background-image: url(/Users/veronika/Documents/FUD/images/bottega-sicula-wpcf_1200x700.jpg);
Картинки все еще не видны(
Я не понимаю пока как это исправить

2019-03-27 19:37 UTC, NikaCrimea commented on Nika/index.html
> +                        <div><a> > DISCOVER THE PROJECT</a></div>
да, так как надо)

2019-03-27 20:18 UTC, seyar commented on Nika/css/style.css
> +.image-1 {
в родительском оставь `background: repeat`, а у деток оставь `background-image: url(...)`

2019-03-27 20:19 UTC, seyar commented on Nika/index.html
> +                        <div><a> > DISCOVER THE PROJECT</a></div>
ты заставляешь меня скачивать твою работу и самому проверять 😠

2019-03-27 20:20 UTC, NikaCrimea commented on Nika/index.html
> +                        <div><a> > DISCOVER THE PROJECT</a></div>
не качай, правда так и надо)

2019-03-27 20:26 UTC, NikaCrimea commented on Nika/css/style.css
> +.image-1 {
а зачем им "background: repeat"? Я же хочу "background-size: cover" сделать)

2019-03-27 20:27 UTC, seyar commented on Nika/css/style.css
> +.image-1 {
это я тебя проверял 👀 

Да, там надо background-size: cover

2019-03-27 20:31 UTC, seyar commented on Nika/index.html
> +                        <div><a> > DISCOVER THE PROJECT</a></div>
просто браузеры сейчас слишком умные и все правильно рендерят
> эх вот в 96м...

короче я намекал на html entities `&lt;`
https://www.w3schools.com/html/html_entities.asp

Сейчас тупой браузер (напрмер, us browser) может перепутать символ `>` и закрывающийся тег. И закроет какой-нибудь див  раньше чем ты рассчитывала и все поедет.

2019-03-27 20:34 UTC, NikaCrimea commented on Nika/index.html
> +                        <div><a> > DISCOVER THE PROJECT</a></div>
ааа, я о таком даже не знала) спасибо, теперь буду знать!

2019-03-27 20:36 UTC, NikaCrimea commented on Nika/index.html
> +                        <div><a> > DISCOVER THE PROJECT</a></div>
так а что с картинками делать? вы их видите? я уже разные способы путей пробовала)

2019-03-27 20:36 UTC, seyar commented on Nika/css/style.css
> +    padding-top: 48px;
паддинги можно объединить в адын

2019-03-27 20:37 UTC, seyar commented on Nika/index.html
> +                        <div><a> > DISCOVER THE PROJECT</a></div>
я когда скачал - их видел. Все норм

2019-03-27 20:39 UTC, NikaCrimea commented on Nika/index.html
> +                        <div><a> > DISCOVER THE PROJECT</a></div>
а почему тогда они не отображаются через http://htmlpreview.github.io/?

2019-03-27 20:41 UTC, NikaCrimea commented on Nika/css/style.css
> +    padding-top: 48px;
эээмм... тут есть некоторый парадокс) когда я их пишу в одном, они не отображаются на странице(

2019-03-28 08:40 UTC, seyar commented on Nika/css/style.css
> +    padding-top: 48px;
тут есть некоторая ошибка тогда. А парадокс это свет которые ведет себя как поток частиц и как волна

2019-03-28 10:59 UTC, NikaCrimea commented on Nika/css/style.css
> +    padding-top: 48px;
я так понимаю здесь проблема в свойстве display?

2019-03-28 13:45 UTC, seyar commented on Nika/css/style.css
> +    padding-top: 48px;
`padding: 48px 14px 8px;`

display не влияет на паддинг. Если не работает, то это может кто-то другой переопределяет свойство. Посмотри в инспекторе, там оно зачеркивается если так. 
И если переопределяет почитай про вес селекторов, если нет - то не читай :)

2019-03-28 13:49 UTC, NikaCrimea commented on Nika/css/style.css
> +    padding-top: 48px;
а я писала вот так `padding: 48px, 14px, 8px, 14px;` и так не работало, а как ты написал, работает)

2019-03-28 13:59 UTC, seyar commented on Nika/css/style.css
> +    padding-top: 48px;
с тебя чай :)

2019-03-29 23:14 UTC, seyar commented
если ревью заглохло, то надо его разворушить. То есть нужно пингануть ревьюеров. Не им (то есть нам) же ходить за тобой и напоминать что у тебя есть тут совершенный код

п.с мне ок. Детально не смотрел, если че потом допушим отдельным пулл реквестом

2019-03-30 05:18 UTC, NikaCrimea commented
> если ревью заглохло, то надо его разворушить. То есть нужно пингануть ревьюеров. Не им (то есть нам) же ходить за тобой и напоминать что у тебя есть тут совершенный код
> 
> п.с мне ок. Детально не смотрел, если че потом допушим отдельным пулл реквестом

 Я знаю, я писала Валику несколько раз, он сказал, что посмотрит позже) Надеюсь уже скоро:)

2019-03-30 14:46 UTC, mokcrimea commented on Nika/index.html
> +                    </div>
@NikaCrimea https://stackoverflow.com/a/29973358

2019-03-30 14:48 UTC, mokcrimea commented
@seyar если тебе ок - жми аппрув, иначе не влить :)

2019-03-30 15:02 UTC, mokcrimea requested changes

2019-03-30 15:02 UTC, mokcrimea commented on Nika/css/style.css
> +    background: url(../images/xdefault.png.pagespeed.ic.uZXACHvpgj.png);
Файлик кстати можно переименовать хотя бы в `logo.png`

2019-03-30 15:02 UTC, mokcrimea commented on Nika/css/style.css
> +
лишний отступ

2019-03-30 15:02 UTC, mokcrimea commented on Nika/index.html
> +                        <div><a> &gt; DISCOVER THE PROJECT</a></div>
А зачем ты тут завернула ссылку в дополнительный div ?
И стили выше еще навесила на `.button div, .button a`. Не достаточно чего-то одного ?

2019-03-30 15:02 UTC, mokcrimea commented on Nika/index.html
> +                        <span><em>We don't just live on Eggplant Parmigiana, cannoli and lemon seltzer .</span></em>
у тебя тут теги закрывающие местами перепутаны
настрой, пожалуйста, форматирование и валидацию в VSCode, что бы избежать таких опечаток

2019-03-30 15:02 UTC, mokcrimea commented on Nika/index.html
> +                        <div><img src="./images/libra.png"></div>
почитай про атрибут `alt` для `<img>`

2019-03-30 15:02 UTC, mokcrimea commented on Nika/index.html
> +                    <hr align="left" width="225" size="1" color="#4d4d4d">
а почему ты ее закрыла ?

2019-03-30 15:02 UTC, mokcrimea commented on Nika/index.html
> +                    <hr align="left" width="225" size="1" color="#4d4d4d">
У тебя дальше по коду повторяются одни и те же атрибуты для тега `<hr>`. Вынеси все в отдельный класс (в css) и пропиши тут.

2019-03-30 15:42 UTC, seyar commented
> @seyar если тебе ок - жми аппрув, иначе не влить :)

ну понятное дело что можно найти еще сотню комментариев. А находить эту сотню мне стало лень. Думал нажать апрув позже если лень не пройдет. Но пожалуй нажму :)

@mokcrimea

2019-03-30 15:42 UTC, seyar approved these changes

2019-03-31 18:22 UTC, NikaCrimea commented on Nika/index.html
> +                    <hr align="left" width="225" size="1" color="#4d4d4d">
исправила)

2019-03-31 22:20 UTC, mokcrimea approved these changes

2019-03-31 22:21 UTC, merged